image: registry.gitlab.fpcomplete.com/fpco/default-build-image:4330

stages:
  - build
  - deploy

build-and-push:
  stage: build
  script:
    - make build-ci-image
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}"

deploy_prod:
  stage: deploy
  script:
    - make deploy
  environment:
    name: production
    url: https://k8s-haskell-webinar.fpcomplete.com
  when: manual
  only:
  - master
