image: registry.gitlab.fpcomplete.com/fpco/default-build-image:4330
build-and-push:
  stage: build
  script:
    - make build-ci-image
    - docker login -u gitlab-ci-token -p "${CI_BUILD_TOKEN}" "${CI_REGISTRY}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_PIPELINE_ID}"
