version: '2'

services:
  myapp:
    build:
      context: .
      args:
        - BINARY_PATH
    image: gitlab.fpcomplete.com/fpco-mirors/haskell-multi-docker-example
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    ports:
      - 3000:3000

